---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  workers:
    type: local
    number: 1
  rounds:

  - label: initLedger
    txNumber: 1             
    rateControl:
      type: fixed-rate
      opts:
        tps: 1
    callback: benchmarks/masterBenchmark/covid-passport/initLedger.js

#  - label: common
#    txDuration: 180
#    rateControl:
#      type: fixed-rate
#      opts:
#        tps: 50
#    callback: benchmarks/masterBenchmark/covid-passport/common.js

  - label: readBlockchain
    txNumber: 1
    rateControl:
      type: fixed-rate
      opts:
        tps: 1
    callback: benchmarks/masterBenchmark/covid-passport/doNothing.js


monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1
