---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  workers:
    type: local
    number: 1
  rounds:

  - label: initLedger
    txNumber: 1             
    rateControl:
      type: fixed-rate
      opts:
        tps: 1
    callback: benchmarks/masterBenchmark/notarization/initLedger.js

  - label: common
    txDuration: 10 #180
    rateControl:
      type: fixed-rate
      opts:
        tps: 10
    callback: benchmarks/masterBenchmark/notarization/common.js

  - label: readBlockchain
    txNumber: 1
    rateControl:
      type: fixed-rate
      opts:
        tps: 1
    callback: benchmarks/masterBenchmark/notarization/doNothing.js


monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1
