---
test:
  workers:
    type: local
    number: 1

  rounds:
  - label: initLedger
    txNumber: 1
    rateControl:
      type: fixed-rate
      opts:
        tps: 1
    callback: benchmarks/masterBenchmark/eureka/initLedger.js

  - label: common
    txDuration: 180
    rateControl:
      type: fixed-rate
      opts:
        tps: 50
    callback: benchmarks/masterBenchmark/eureka/common.js

  - label: readBlockchain
    txNumber: 1
    rateControl:
      type: fixed-rate
      opts:
        tps: 1
    callback: benchmarks/masterBenchmark/eureka/doNothing.js

monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1
